### ISSUE TITLE
HTTPS Everywhere

### ISSUE THREAD

**Issue by CalvinRodo** [gcdevops/HRWhiteListing#104]
All data must be encrypted in transit

**Comment by ben851** [comment]
Traefik ensuring end to end client HTTPS. Internal communication is currently mix of HTTPS and HTTP.

**Comment by CalvinRodo** [comment]
If it's possible to have all internal traffic be secure that would be ideal, but I think the most important requirement is for all external facing traffic.

**Comment by EricDube** [comment]
HTTPS is being enforced by Traefik so we will close this ticket and use #155 to discuss internal HTTPS between Traefik and the solutions.
