### ISSUE TITLE
Data Encrypted at Rest

### ISSUE THREAD

**Issue by CalvinRodo** [gcdevops/HRWhiteListing#105]
All data at rest must be encrypted

**Comment by ben851** [comment]
Not sure why this is a backlog item - azure managed disks are encrypted at rest by default.

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/managed-disks-overview

Unless I'm missing something.

**Comment by CalvinRodo** [comment]
Just throwing in some security items that are required for PB, if it's already done then that's okay.

**Comment by CalvinRodo** [comment]
It'll need to be tracked in case you have to go through an SA&A
