### ISSUE TITLE
Platform: AU-3 | Persistance Audit Logs

### ISSUE THREAD

**Issue by CalvinRodo** [gcdevops/HRWhiteListing#106]
The information system generates audit records containing information that establishes what type of event occurred, when the event occurred, where the event occurred, the source of the event, the outcome of the event, and the identity of any individuals or subjects associated with the event.

All access to PB fields must be tracked and tied to user account of viewer
This should track: 
 - Modification of PB Data fields
 - Access to PB Data fields

**Comment by jaysonmc** [comment]
PB controls do not apply, but auditing/logging has been put in place
https://github.com/gcdevops/OdooDocker/pull/61
