### ISSUE TITLE
Security Questionnaire

### ISSUE THREAD

**Issue by CalvinRodo** [gcdevops/HRWhiteListing#110]
This is not mandatory at this time, but is being used to track in case you need to go through the SA&A Process.

**Comment by jaysonmc** [comment]
Is there a link to said questionnaire?

**Comment by CalvinRodo** [comment]
you'd have to contact IT Security for it, I have an unfilled old version and a filled out new version but it becomes classified PB when filled so would have to be stored and filled out on prem

**Comment by CalvinRodo** [comment]
Nathalie Thibault should be able to provide.

**Comment by jaysonmc** [comment]
Completed. Included in e-mail to CIO for ATO
Not sent to security yet, but complete (and stored on network)
