### ISSUE TITLE
RA-5 Vulnerability Scanning and SI-5  Security Alerts, Advisories, And Directives

### ISSUE THREAD

**Issue by CalvinRodo** [gcdevops/HRWhiteListing#116]
Either vulnerability scanning using a tool such as Clair (or the departmental standard which I believe is an Aqua tool) or you should subscribe to SSC Security alerts, or possibly monitor CVE's for odoo yourself: https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=odoo

**Comment by jaysonmc** [comment]
Related to #172

**Comment by jaysonmc** [comment]
@jaysonmc
