### ISSUE TITLE
Dataflow/Network Diagram

### ISSUE THREAD

**Issue by CalvinRodo** [gcdevops/HRWhiteListing#117]
A diagram outlining all the systems, how they communicate (port/protocol, type of data), users interacting with the system and actions taken. 

Ideally this would be generated as much as possible from your actual infrastructure or your infrastructure as code. 

This will be used as input into SA&A and ATO process. Will also be required for Privacy Checklist.

**Comment by ben851** [comment]
Production network model diagram:
https://confluence.dts-stn.com/display/DEV/GRH-HRM+Production+Model

Production DNS routing diagram
https://confluence.dts-stn.com/display/DEV/GRH-HRM+DNS+Model

Technology Stack:
https://confluence.dts-stn.com/display/DEV/GRH-HRM+Technology+Stack
