### ISSUE TITLE
Add in classification data

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#125]
When you click and employee and navigate to the "Work information tab" in edit mode, the "Classification" (last row, first column on the left) is empty

Populate with the following data
https://docs.google.com/document/d/1LigJp2_tImpOqjLBHbttM8b9tVHJTtz2lwXdXCRUPOE/edit?usp=sharing

**Comment by Moro-Code** [comment]
Guessing we don't need levels for classification ?

**Comment by jaysonmc** [comment]
Script built to scape values

**Comment by jaysonmc** [comment]
Waiting on 
https://github.com/gcdevops/HRWhiteListing/issues/263

**Comment by Moro-Code** [comment]
Will use the following to get classification data

**Comment by Moro-Code** [comment]
classification added to importer
