### ISSUE TITLE
Add region custom field

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#128]
Added to requirements

Data should be on GEDS

Add a field to track which region the employee works in

**Comment by Moro-Code** [comment]
Data is not in GEDS as we now realized, it is based on what ADM you are assigned to

Atlantic Region: Sara Filbee, ADM
·      BMS: Carson Littlejohn, DG, ISB
o  Delegated to Kyla Mullin
 
Quebec Region: Claire Caloren, ADM
·      BMS: Philippe Emond
o  Delegated to Melanie Gauthier
 
Ontario Region: Mary Ann Triggs
·      BMS: Aretha Constant
o  Delegated to Carmen Yung
 
Western-Territories Region: Sylvie Bérubé
·      BMS: Cam King
o  Delegated to Jennifer Cooper

We need to create a drop down that auto-populates the region based on your managers region. 

We could probably use an onchange decorator to get the managers region if the parent_id for the employee changes. 
https://www.odoo.com/documentation/13.0/howtos/backend.html#onchange

There should be an example of a selection field already in the hr.employee model
