### ISSUE TITLE
Add VPN Connectivity Field

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#133]
Add custom field

VPN Connectivity method
- VPN
- AppGate

[Added to the MVP documentation](https://docs.google.com/document/d/1FMkkQMBasODcdnTb_bGLd-dM5Qe-sc1S-GIcRshwtKM/edit?usp=sharing)

And populate data (@jaysonmc will send)

**Comment by Moro-Code** [comment]
We already have this custom field 
![Screen Shot 2020-04-07 at 10 04 46 AM](https://user-images.githubusercontent.com/26819992/78678637-3a426700-78b7-11ea-898d-d4cf9e415db9.png)

**Comment by jaysonmc** [comment]
Oh, I am blind. Thanks!
