### ISSUE TITLE
Implement application logging

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#148]
To meet the following security requirement

Based on #147

"Implement an audit process for the auditable events identified.
Note: You may only need to configure your solution to send the audit log records to a centralized logging facility, if one is available, where existing auditing mechanisms will be applied."

Please include logging that is in place for the application, either as 
- a detailed comment or
- a link to documentation, or
- list of tasks that were implemented to address this

**Comment by jaysonmc** [comment]
Related to #150

**Comment by Moro-Code** [comment]
We get log in attempt logging for free from odoo. Logs are outputed to stdout by default 
https://www.odoo.com/documentation/13.0/setup/deploy.html#blocking-brute-force-attacks

**Comment by Moro-Code** [comment]
This works really well https://github.com/OCA/server-tools/tree/13.0/auditlog
opening PR

**Comment by jaysonmc** [comment]
What is the status of persisting these logs on dev/staging/prod?
