### ISSUE TITLE
Introduce Dev Team

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#15]

**Comment by Moro-Code** [comment]
Dumped info to gc-tools channel on DTS slack with all the information I currently know. As information comes in, will update

**Comment by Moro-Code** [comment]
The Directory app was a tool that the GCTools was building to fill the need of providing a dynamic directory of employees across the GoC. 

There are three main components to this application.

1)  Concierge Service, more commonly known as GCAccount. This is a custom OpenID SSO system build in Django

[repo](https://github.com/gctools-outilsgc/concierge)

2) Profile service. This is a graphql endpoint built on Apollo Server and a database abstraction tool called Prisma in which you define your database schema as a GraphQL type schema and it will handle creating a GraphQL endpoint for you, as well as migrations, deployment ect. The profile service talks to the SSO service via a message queue called RabbitMQ to validate tokens 

[prisma tool](https://www.prisma.io)
[repo](https://github.com/gctools-outilsgc/profile_service)


3) Front end built in react. Using the aurora design system which was supposed to be the next iteration of the canada.ca design system

[design system](https://design.gccollab.ca/)
[repo](https://github.com/gctools-outilsgc/directory-fe)

The general architecture and design philosophy can be documented here 

[architecture documentaton](https://documentation.beta.gccollab.ca/profile/introduction)

There is also a microservice template to reduce the need for writing boilerplate code to interface with these services 

[repo](https://github.com/gctools-outilsgc/micro_service_template)
