### ISSUE TITLE
Implement key management procedures

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#152]
Security requirement.

Please document how we are securing keys required for the application

- Detailed comment in this issue
- Reference to documentation
- An issue or PR that addresses this issue

**Comment by CalvinRodo** [comment]
Things to consider: 

 - Where key's are stored
 - How keys are rotated
 - Who has access and is doing this

**Comment by jaysonmc** [comment]
https://azure.microsoft.com/en-ca/services/key-vault/

@EricDube please document implementation regarding @CalvinRodo's comments, then close (if met, which I am assuming is the case with default functionality)

**Comment by EricDube** [comment]
The keys are currently stored in Azure KeyVault and a TTL has been set. The ops team for this project has access to the keys and are able to rotate before TTL is up.
