### ISSUE TITLE
Document how to create a new login user

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#177]
Either document it and put a link or put it in this PR. Instructions will need to be added to the documentation below, that seems to conflate employees with users

https://drive.google.com/file/d/1o6TxmYYedc5Afe33J_Hoe4Imp_EKWAbO/view?usp=sharing

**Comment by jaysonmc** [comment]
@jaysonmc review

**Comment by jaysonmc** [comment]
@ElminaIusifova 
The document seems to have how to create and remove an employee, which this is distinct from a user. 

It is my understanding that a user can login. Just because someone is an employee, doesn't neccessarily mean they are a user

**Comment by gabrielcossette** [comment]
@ElminaIusifova Do you want my help?

**Comment by ElminaIusifova** [comment]
@gabrielcossette  merci
