### ISSUE TITLE
Rename skills to profiles

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#195]
Right now an employee has a list of skills, rename this to profiles

**Comment by gabrielcossette** [comment]
@jaysonmc How would you call the items beneath the profiles, e.g.:

**1. Employment Insurance (EI)**

- Call centres
- Claims processing

Areas or Domains maybe?

Thanks!

**Comment by jaysonmc** [comment]
@gabrielcossette 

Enabling services
