### ISSUE TITLE
Request official DNS

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#2]

**Comment by ben851** [comment]
@jaysonmc @Telecoaster I'm going to need some sort of name/naming convention for this thing so I can open the request with SSC. Please advise.

**Comment by jaysonmc** [comment]
grh-hrm.edsc-esdc.canada.ca

**Comment by CalvinRodo** [comment]
you should see if you can just get ownership of the esdc-esdc domain similar to how CDS did with Alpah.canada.ca where they got SSC to I believe point CDS' AWS Nameservers to them so they could automate using terraform.

**Comment by jaysonmc** [comment]
This is a good idea @CalvinRodo. We could include this in the request.

Or perhaps ask for grh-hrm.edsc-esdc.canada.ca (and the ability to add subdomains to it ourselves as we need), and also ask about ownership of edsc-esdc, though wouldn't let that delay progress on the initial request.

@ben851 or @Telecoaster, thoughts?

**Comment by Telecoaster** [comment]
DNS request submitted to SSC for grh-hrm.edsc-esdc.canada.ca
