### ISSUE TITLE
Change "Create" button style

### ISSUE THREAD

**Issue by ElminaIusifova** [gcdevops/HRWhiteListing#209]
In order to make it more user friendly modify the "Create" button:
-change "Create" -> "Add Employee";
-change the size of the button and make it more visible;
-place it above the employee list  table 

<img width="820" alt="Screen Shot 2020-04-16 at 11 56 53 AM" src="https://user-images.githubusercontent.com/32398063/79480854-ab32fe80-7fdc-11ea-8e6b-5a978c82f8f5.png">

**Comment by will0684** [comment]
@ElminaIusifova what do you think about this?

<img width="1098" alt="Screen Shot 2020-05-01 at 12 52 57 PM" src="https://user-images.githubusercontent.com/31868510/80823491-bc6a3680-8baa-11ea-9e53-81594333af09.png">

**Comment by ElminaIusifova** [comment]
@will0684 yes it is perfect, can you add "+"  icon to the button?

**Comment by will0684** [comment]
Sure let me see

**Comment by will0684** [comment]
@ElminaIusifova what about this?

You can test it in my branch as well: modify-create-butto

![Screen Shot 2020-05-04 at 12 40 29 PM](https://user-images.githubusercontent.com/31868510/80990563-80caa900-8e04-11ea-8b67-aecd989afc12.png)

**Comment by will0684** [comment]
Approved version:

![Screen Shot 2020-05-04 at 1 03 15 PM](https://user-images.githubusercontent.com/31868510/80992706-eb311880-8e07-11ea-9c5d-800a2314ad4c.png)
