### ISSUE TITLE
Modify the Add Employee form

### ISSUE THREAD

**Issue by ElminaIusifova** [gcdevops/HRWhiteListing#210]
1. Remove purple background colour on the Employee Name
2. Change the style of the note  (fon-size, remove bold, change color, maybe add background-color); Ex:

<img width="568" alt="Screen Shot 2020-04-16 at 12 30 09 PM" src="https://user-images.githubusercontent.com/32398063/79486246-6ca14200-7fe4-11ea-8faa-bebb572ebe23.png">

3. Tab Content: remove bold, change font-size

**Comment by will0684** [comment]
<img width="1080" alt="Screen Shot 2020-04-27 at 12 27 45 PM" src="https://user-images.githubusercontent.com/31868510/80396391-8ebb7f80-8882-11ea-824c-c5f8aea4776a.png">

I changed the background colour of the field as you can see here. For the "note" you're referring to do you mean this notification toast?

<img width="842" alt="Screen Shot 2020-04-27 at 12 29 22 PM" src="https://user-images.githubusercontent.com/31868510/80396561-cb877680-8882-11ea-934c-97ddb6474ff5.png">

If so, were there specific changes you wanted?

**Comment by ElminaIusifova** [comment]
@will0684  by note I mean this content: 

"Please note all information contained within these tabs are considered Protected information and should be handled in accordance with departmental and Government of Canada directives, policies and laws". 

Maybe something like that?  
![Help25-note-form-field-classes-screenshot](https://user-images.githubusercontent.com/32398063/80499171-a2c2b800-893a-11ea-9cd4-1a79865e6e17.png)

**Comment by will0684** [comment]
Could you let me know where that screen is? I am not exactly sure where to find it. @ElminaIusifova
