### ISSUE TITLE
Investigate tool to scan docker image for vulnerabilities/controls

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#211]

**Comment by jaysonmc** [comment]
Related to #173

**Comment by e-wu** [comment]
Using anchore to scan docker image for vulnerabilities inl library.
Ran apt update and still found erors
Will include pip update too.

**Comment by e-wu** [comment]
No longer running upgrades as subsequent runs don't guarantee as is copies. Relying on upstream images to provide updates as last anchore scan results in very little vulnerabilities. 

To produce a report json that can be imported into SecurityDojo, look at the README
https://github.com/gcdevops/OdooSecurityTooling/tree/master/docker-security/anchore
