### ISSUE TITLE
Hide My Odoo.com account & Support

### ISSUE THREAD

**Issue by ElminaIusifova** [gcdevops/HRWhiteListing#218]
<img width="229" alt="Screen Shot 2020-04-16 at 2 48 40 PM" src="https://user-images.githubusercontent.com/32398063/79494795-97de5e00-7ff1-11ea-8e99-c60dbed51bdd.png">

**Comment by jaysonmc** [comment]
Also side the "Support" button above "My Odoo.com account"

**Comment by jaysonmc** [comment]
Could do 
https://github.com/gcdevops/HRWhiteListing/issues/219
at the same time
