### ISSUE TITLE
Hide Shortcut and include shortcuts to the User manual

### ISSUE THREAD

**Issue by ElminaIusifova** [gcdevops/HRWhiteListing#219]
<img width="217" alt="Screen Shot 2020-04-16 at 3 00 47 PM" src="https://user-images.githubusercontent.com/32398063/79496668-73d04c00-7ff4-11ea-8fa9-6974f73a0f8e.png">

**Comment by ElminaIusifova** [comment]
Shortcuts are added to the User manual. Just hide it from the menu

**Comment by gabrielcossette** [comment]
I believe this has been done. Feel free to reopen if not.
