### ISSUE TITLE
Document Prod Data Backup Process

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#223]
CP-6 | Alternate Storage Site

(A) The organization establishes an alternate storage site including necessary agreements to permit the storage and retrieval of information system backup information.

CP-9 | Information System Backup

(A) The organization conducts backups of user-level information contained in the information system [Assignment: organization-defined frequency consistent with recovery time and recovery point objectives].
(B) The organization conducts backups of system-level information contained in the information system [Assignment: organization-defined frequency consistent with recovery time and recovery point objectives].
(C) The organization conducts backups of information system documentation including security-related documentation [Assignment: organization-defined frequency consistent with recovery time and recovery point objectives].
(D) The organization protects the confidentiality, integrity, and availability of backup information at storage locations.
(AA) The organization determines retention periods for essential business information and archived backups.

-----------------------------------

Implement a backup and restore process for the GC data maintained in your solution.

**Comment by jaysonmc** [comment]
@EricDube @floo0025 

If implementation details are provided as to how we manage backups, many of these can likely be satisfied by out of the box Azure functionality (depending on the toolset we're leveraging of course).

Any information helping to document compliance with the above would be helpful.

**Comment by floo0025** [comment]
@jaysonmc For platform backups, if we're following current DTS practice backups are handled by a scheduled Jenkins job that takes daily snapshots of each disk. Azure's backup service is an option, but the cost overhead is a fair bit higher. I don't know if that is considered enough for Prod/IT Sec/business continuity though. Does it need a separate data export from the disk? What is the retention period? Ours is 30 days, is yours longer? Restoration is a couple button clicks, but does it have to be tested (I don't recall SADE testing on-prem...)? This is SLA stuff we'd have to determine

**Comment by floo0025** [comment]
@jaysonmc Current backup strategy writeup, including future PBMM considerations, is up at:
https://drive.google.com/open?id=14iJUEh6SMWcu4NOI7dpMcEWI48G3a1pvqnAtRWPLlMI
