### ISSUE TITLE
Create organisation structure 

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#28]

**Comment by gabrielcossette** [comment]
Haven't found an UI to import departments (teams), so we'll need to go through the database (using pgAdmin) and import a CSV there. We also need to increment the "Sequence" setting for the unique ID.

**Comment by Moro-Code** [comment]
We can develop a module for this I think, can do it manually yes, however odoo has their own ORM with it's quirks so I do not recommend doing it manually

**Comment by jaysonmc** [comment]
Depends on #49

**Comment by Moro-Code** [comment]
GEDS data imported to the best of my ability 

![Screen Shot 2020-03-29 at 11 12 48 PM](https://user-images.githubusercontent.com/26819992/77873439-fe086a00-7217-11ea-85af-924ce849b418.png)
