### ISSUE TITLE
Automating data importation process

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#295]

**Comment by Moro-Code** [comment]
Currently set up for staging and will set up for prod this weekend https://github.com/gcdevops/OdooImport

**Comment by Moro-Code** [comment]
Tested and working on production. Import scheduled to run during the evening

**Comment by Moro-Code** [comment]
Accidentally tested during data importation process. Node crashed and rebooted, as expected. Resources are limited to single node, as ELB not implemented
