### ISSUE TITLE
Request production env

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#3]

**Comment by Telecoaster** [comment]
Exception request for PB Cloud submitted by Martin Mondor.  Additional project info given to IT Sec triage (Stanislaw Ozorowski) for clarification.

Green light to engage Specialized Environments to begin provisioning environments while we wait for CIO approval.  I have submitted a request to the SE, IT Sec and Cloud CoE teams to begin work asap.

**Comment by Telecoaster** [comment]
Update from Cloud CoE:  Production environment is expected to be ready for testing by CoB tomorrow.  Full PB environment expected by CoB Monday.

**Comment by Telecoaster** [comment]
Prod cloud environment ready, deployment of base infrastructure underway.

**Comment by Telecoaster** [comment]
Microsoft blocking creation of new VM's due to COVID-19 load.  Ticket opened with Microsoft and escalated to executive management.

**Comment by Telecoaster** [comment]
Production environment provisioned and ready for product deployment
