### ISSUE TITLE
Document Tech Stack

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#32]
In the Google Drive in the Technical Folder, template for tech stack is there (not that you have to use that, but just for a place to put it).

**Comment by floo0025** [comment]
Azure Architecture, Deployment and Orchestration Model diagrams
https://confluence.dts-stn.com/display/DEV/GRH-HRM+Production+Model

Stack
https://confluence.dts-stn.com/display/DEV/GRH-HRM+Technology+StackOdoo

Local Docker Instance
https://confluence.dts-stn.com/display/DEV/Odoo+Local+Docker+Instance

Database Schema
https://confluence.dts-stn.com/display/DEV/GRH-HRM+Database+Schema

Install guide (Terraform + Helm + Jenkins) to follow

**Comment by floo0025** [comment]
Support manual, v1, is up at https://drive.google.com/drive/folders/1YYTkeaX9ClkP2UduWZHt7lgEGVu1xCML

Install guide will be part of the support manual.

**Comment by jaysonmc** [comment]
Could we add the list of documents provided above to one of the files in Google docs? Easier to track than just in the issues here

**Comment by floo0025** [comment]
Azure Architecture and Deployment/Orchestration Diagram
https://drive.google.com/open?id=1gkvZI1yTD1nstgoceMGZVEYWkpLSTlNF

Technology Stack
https://drive.google.com/open?id=1QyxIRZf1KsGIlMSeoEoDaOaMBIulGG-T

Odoo Local Docker Instance
https://drive.google.com/open?id=1PulNtrVkSwiMlgQv63IjTUH90Eisj7xk

Database Schema
https://drive.google.com/open?id=1WvoyS9Ut_TitVslALsbNw2NXUnxMGSWb

PBMM Deployment Instructions
https://drive.google.com/open?id=1DgWY35Qo_w5zWbP0Ref6gzEysTVM8-Ei
