### ISSUE TITLE
Configure infrastructure CI/CD

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#4]

**Comment by ben851** [comment]
Jenkins is running, need to create pipeline

**Comment by ben851** [comment]
Unable to do infrastructure automation with terraform due to cloud security policies adding explicit null fields to our kubernetes cluster. This causes terraform to think there are discrepancies between the state and cloud deployment forcing it to delete the existing cluster and re-create.

**Comment by ben851** [comment]
Basic infrastructure CICD implemented - currently doing dry-run only due to active development
