### ISSUE TITLE
Rename Employees to My Team and Employee Directory to Public Directory

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#64]
Employees and Employee director (top navigation) does the same thing

**Comment by will0684** [comment]
One slight difference between the two views, one is the **hr_employee_view** and the other is **hr_employee_public_view**

**hr_employee_view**

<img width="551" alt="Screen Shot 2020-04-01 at 5 43 38 PM" src="https://user-images.githubusercontent.com/31868510/78189754-a00a9b00-7440-11ea-9cc7-b108a038d4fe.png">

**hr_employee_public_view**

<img width="550" alt="Screen Shot 2020-04-01 at 5 43 46 PM" src="https://user-images.githubusercontent.com/31868510/78189764-a436b880-7440-11ea-913b-97bc90bf4f76.png">

**Comment by Moro-Code** [comment]
@will0684 Very very good catch. Perhaps we can do a hacky thing where admins are not allowed access to the public view

**Comment by gabrielcossette** [comment]
As #98, menu items have already been removed in dev and staging environments. Need to add automation (adding label).

**Comment by Moro-Code** [comment]
Blocked here, cannot remove menuitem from custom module, can create a user group from which no one is a part of and then specify that menu item to show only for users of that group. However this is hacky
