### ISSUE TITLE
Data sanitization

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#7]

**Comment by Moro-Code** [comment]
Need data sources from which to clean

**Comment by Telecoaster** [comment]
Located datafile and sent to @jaysonmc 's work email

**Comment by jaysonmc** [comment]
@Moro-Code There is also a link under the Data header in the All Requirements document in the Google Drive

**Comment by jaysonmc** [comment]
No longer relevant. 

Replaced by #28 and #58
