### ISSUE TITLE
Add Sub Fields to Skills

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#76]
- [x] Jayson to supply list of sub categories
- [x] Add to application

**Comment by jaysonmc** [comment]
https://github.com/gcdevops/HRWhiteListing/issues/56

**Comment by jaysonmc** [comment]
#80

**Comment by jaysonmc** [comment]
https://drive.google.com/file/d/1BH7RQrwn200Ux71UNSD8sOIHethzUvIK/view?usp=sharing

**Comment by gabrielcossette** [comment]
Added to Dev and Staging. Needs automation. CSV I used to import:
https://drive.google.com/file/d/1Yb56oPDNhBH-jo-R5vk5vijepMdn3V7J/view?usp=sharing

**Comment by gabrielcossette** [comment]
@jaysonmc Can you identify which skills categories (those numbered 1.-17.) need a skill with the name of the category?

E.g. 
**1. Employment Insurance (EI)**

- Call centres
- Claims processing
- Work-Sharing – agreement approval and EI eligibility determination and processing

Do we need the skill **Employment Insurance (EI)** or not?

Also, the list will need more cleanup but that's ok for now.

**Comment by jaysonmc** [comment]
Added to MVP and All Reqs documents
