### ISSUE TITLE
Configure/test user access for MVP

### ISSUE THREAD

**Issue by gabrielcossette** [gcdevops/HRWhiteListing#85]

**Comment by jaysonmc** [comment]
Second user type in the MVP document outlines access requirements for managers

https://docs.google.com/document/d/1FMkkQMBasODcdnTb_bGLd-dM5Qe-sc1S-GIcRshwtKM/edit?usp=sharing

**Comment by gabrielcossette** [comment]
User access for MVP configured in both Dev and Staging. Need to add automation.

Basically, senior management must be added to group **Employees / Officer** and this Record Rule must be configured:

Name: **Senior Management**
Object: **Employee**
Apply for: **Create, Write, Delete**
Groups: **Employees / Officer**
Rule Definition:
**[('id', 'child_of', [employee.id for employee in user.employee_ids])]**

**Comment by gabrielcossette** [comment]
I created a new group **Employee / Senior Management** instead of reusing **Officer**

Reason is that group **Employees / Administrator** inherits **Officer** so if we add a Record Rule for Officer, it also affects Employees Administrators (us).

**Comment by Moro-Code** [comment]
For your record rule it looks like you are applying this to 

> Groups: Employees / Officer

Could you confirm this is correct ? I would assume you need to apply this to Employees / Senior Management no ?

**Comment by gabrielcossette** [comment]
> 
> 
> For your record rule it looks like you are applying this to
> 
> > Groups: Employees / Officer
> 
> Could you confirm this is correct ? I would assume you need to apply this to Employees / Senior Management no ?

Sorry, my bad. You are right, updated my comment.
